version: "3"

services: 
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - "8001:5000"
        volumes: 
            - .:/app
        command: >
            sh -c "python app.py 0.0.0.0:8001"
        environment:
            - DB_HOST=db
            - DB_NAME=ms_admin
            - DB_USER=root
            - DB_PASSWORD=root
        depends_on: 
            - db
    
    queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: >
            sh -c "python consumer.py"
        depends_on: 
            - db
    
    db:
        image: mysql:5.7.22
        restart: always
        environment: 
            - MYSQL_DATABASE=ms_main
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 33067:3306

volumes:
    mysqldata: